services:
  gateway:
    image: traefik:v2.10
    container_name: gateway_e2e
    mem_limit: 256m
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      # - "--providers.file.filename=/etc/traefik/traefik.dynamic.yml"

      #prometheus
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addrouterslabels=true"
      - "--metrics.prometheus.addserviceslabels=true"
      - "--metrics.prometheus.entrypoint=metrics"
      - "--entrypoints.metrics.address=:8899"
    ports:
      - "8080:8080"
      - "80:80"
      - "8899:8899"
    networks:
      - rabbitmq_nodejs
      - postgres_nodejs
      - total
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # - "./traefik.dynamic.yml:/etc/traefik/traefik.dynamic.yml:ro"
    depends_on:
      - auth

  rabbitmq:
    image: rabbitmq:4.0-management-alpine
    container_name: rabbitmq_e2e
    mem_limit: 256m
    ports:
      - 5673:5672
      - 15673:15672
    networks:
      - rabbitmq_nodejs
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  postgres:
    image: postgres:14.5-alpine
    container_name: postgres_e2e
    mem_limit: 384m
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - postgres_nodejs
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  auth:
    build: 
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth_e2e
    mem_limit: 384m
    env_file:
      - .env
    ports:
      - "3002:3002"
    networks:
      - total
      - rabbitmq_nodejs
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      FIREBASE_API_KEY: ${FIREBASE_API_KEY}
      FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
      FIREBASE_MESSAGING_SENDER_ID: ${FIREBASE_MESSAGING_SENDER_ID}
      FIREBASE_APP_ID: ${FIREBASE_APP_ID}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=PathPrefix(`/api/auth`)"
      - "traefik.http.routers.auth.entrypoints=web"
      - "traefik.http.services.auth.loadbalancer.server.port=3002"

  profile:
    build: 
      context: ./profile
      dockerfile: Dockerfile
    container_name: profile_e2e
    mem_limit: 384m
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
      - auth
    ports:
      - "3003:3003"
    networks:
      - rabbitmq_nodejs
      - postgres_nodejs
      - total
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      FIREBASE_API_KEY: ${FIREBASE_API_KEY}
      FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
      FIREBASE_MESSAGING_SENDER_ID: ${FIREBASE_MESSAGING_SENDER_ID}
      FIREBASE_APP_ID: ${FIREBASE_APP_ID}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.profile.rule=PathPrefix(`/api/profile`)"
      - "traefik.http.routers.profile.entrypoints=web"
      # - "traefik.http.routers.profile.middlewares=auth@file"
      - "traefik.http.services.profile.loadbalancer.server.port=3003"

  interaction:
    build: 
      context: ./interaction
      dockerfile: Dockerfile
    container_name: interaction_e2e
    mem_limit: 384m
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - auth
    ports:
      - "3001:3001"
    networks:
      - rabbitmq_nodejs
      - total
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      FIREBASE_API_KEY: ${FIREBASE_API_KEY}
      FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
      FIREBASE_MESSAGING_SENDER_ID: ${FIREBASE_MESSAGING_SENDER_ID}
      FIREBASE_APP_ID: ${FIREBASE_APP_ID}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      MONGO_URI: ${MONGO_URI}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.interaction.rule=PathPrefix(`/api/interaction`)"
      - "traefik.http.routers.interaction.entrypoints=web"
      # - "traefik.http.routers.interaction.middlewares=auth@file"
      - "traefik.http.services.interaction.loadbalancer.server.port=3001"

  e2e_test:
    build: 
      context: ./e2e_test
      dockerfile: Dockerfile
    container_name: e2e_test
    depends_on:
      - auth
      - profile
      - interaction
      - postgres
      - rabbitmq
    networks:
      - rabbitmq_nodejs
      - postgres_nodejs
      - total
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
      TEST_BASE_URL: http://gateway:80

networks:
  rabbitmq_nodejs:
    driver: bridge
  postgres_nodejs:
    driver: bridge
  total:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: