global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'traefik'
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'gateway:8899'

  - job_name: 'auth_service'
    scrape_interval: 5s
    metrics_path: /api/auth/metrics
    static_configs:
      - targets: ['auth:3002']

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - cadvisor:8080