apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: 367074/auth:latest
          env:
            - name: AMQP_URL
              value: amqp://guest:guest@rabbitmq:5672
            - name: FIREBASE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: firebase-secrets
                  key: FIREBASE_API_KEY
            - name: FIREBASE_AUTH_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: firebase-secrets
                  key: FIREBASE_AUTH_DOMAIN
            - name: FIREBASE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: firebase-secrets
                  key: FIREBASE_PROJECT_ID
            - name: FIREBASE_STORAGE_BUCKET
              valueFrom:
                secretKeyRef:
                  name: firebase-secrets
                  key: FIREBASE_STORAGE_BUCKET
            - name: FIREBASE_MESSAGING_SENDER_ID
              valueFrom:
                secretKeyRef:
                  name: firebase-secrets
                  key: FIREBASE_MESSAGING_SENDER_ID
            - name: FIREBASE_APP_ID
              valueFrom:
                secretKeyRef:
                  name: firebase-secrets
                  key: FIREBASE_APP_ID
            - name: FIREBASE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: firebase-secrets
                  key: FIREBASE_PRIVATE_KEY
            - name: FIREBASE_CLIENT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: firebase-secrets
                  key: FIREBASE_CLIENT_EMAIL
          ports:
            - containerPort: 3002