name: Continuous Integration

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ interaction ]

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm ci
        working-directory: ./${{ matrix.service }}
        
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ interaction ]

    defaults:
      run:
        working-directory: ./${{ matrix.service }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Run tests
        env:
          NODE_ENV: test
        run: npm test
        working-directory: ./${{ matrix.service }}