name: Debug Workflow Run

on:
  workflow_run:
    workflows: [ Testing for Interaction Service ]
    branches: [ development ]
    types:
      - completed

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print event context
        run: echo "${{ toJson(github.event) }}"