name: DockerHub Publish

on:
  release:
    types: [ created ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write        

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Auth Service
        uses: docker/build-push-action@v3
        with:
          context: ./auth
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/auth:latest
          no-cache: true
  
      - name: Build and Push Interaction Service
        uses: docker/build-push-action@v3
        with:
          context: ./interaction
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/interaction:latest
          no-cache: true
  
      - name: Build and Push Profile Service
        uses: docker/build-push-action@v3
        with:
          context: ./profile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/profile:latest
          no-cache: true