name: SonarCloud Scanning
on:
  workflow_run:
    workflows: [ "Testing for Interaction Service" ]
    branches: [ development ]
    types: [ completed ]

jobs:
  sonarqube-interaction-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./interaction
    steps:
      # Add debugging steps first
      - name: Print Workflow Info
        run: |
          echo "Workflow Conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Workflow ID: ${{ github.event.workflow_run.id }}"
          echo "Workflow Repository: ${{ github.event.workflow_run.repository }}"
      
      # Only then evaluate the condition
      - name: Evaluate Condition
        if: github.event.workflow_run.conclusion == 'success'
        run: |
          echo "Condition passed, proceeding..."
          
      # Rest of your steps...
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: npm ci
      - name: Run tests with coverage
        run: npm run test
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}