name: SonarCloud Scan

on:
  workflow_run:
    workflows: [ Testing ]
    types: [ completed ]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'

  sonarqube-interaction-service:
    name: SonarQube-interaction-service
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./interaction

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: npm ci
      - name: Run tests with coverage
        run: npm run test
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
