name: SonarCloud Scan2

on:
  push:
    branches:
      - development
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube-interaction-service:
    name: SonarQube-interaction-service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./interaction
        
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: Install Dependencies
        run: npm ci          
      - name: Run tests with coverage
        run: npm run test
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}